[build-system]
requires = [
    "setuptools",
    "setuptools_scm",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py{37,38,39}
skip_missing_interpreters = True

[testenv]
commands = pytest
deps = 
  pytest >= 4, <5
extras =
  test
"""
